#!/bin/sh

if [ $# -lt 1 ]; then
	echo "usage: $0 binary-path [binary-args ...]" > /dev/stderr
	exit 1
fi

rm -f tracemips.fifo
mkfifo tracemips.fifo
./tmips -x $* > tracemips.fifo 2>&1 &
./tracesym "$1" tracemips.fifo | less -S

