#!/bin/sh

if [ $# -ne 2 ]; then
	echo "usage: $0 binary-path trace" > /dev/stderr
	exit 1
fi

./objdump -d "$1" | awk '/^0/ { gsub("[<>:]", "", $2); symbol=$2; } NR == FNR && /^ / { text[$1]=symbol } NR != FNR { printf "%-98s # %s\n", $0, text[$1] }' - "$2"

